language: node_js
node_js:
  - "6"
script:
  - npm install -g serverless@1.23.0
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run deploy-prod; fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then npm run deploy-dev; fi
branches:
  only:
  - master
  - develop